/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMulticall } from "./IMulticall";
export type { UniswapInterfaceMulticall } from "./UniswapInterfaceMulticall";

export { IMulticall__factory } from "./factories/IMulticall__factory";
export { UniswapInterfaceMulticall__factory } from "./factories/UniswapInterfaceMulticall__factory";
